name: BYM
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
  
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  wifi_scan: ^0.4.1
  wifi_iot: ^0.3.19
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.5
  hex: ^0.2.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  dio: ^5.4.3+1
  common_utils: ^2.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.7
  fl_chart: ^0.67.0
  crypto: ^3.0.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.1
  table_calendar: ^3.0.9
  percent_indicator: ^4.2.3
  mobile_scanner: ^5.1.1
  plugin_platform_interface: ^2.1.8
  flutter_blue_plus: ^1.32.7
  logger: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/mine/bindAgent/
    - assets/ic_mine.svg
    - assets/ic_overview.svg
    - assets/ic_station.svg
    - assets/ic_fail.svg
    - assets/ic_logo.png
    - assets/ic_success.svg
    - assets/ic_current_power.svg
    - assets/ic_capacity.svg 
    - assets/ic_photovoltaic_panels.png
    - assets/ic_device_online.svg
    - assets/ic_device_offline.svg
    - assets/ic_device_fault.svg
    - assets/ic_energy_static.svg
    - assets/ic_plant_more.svg
    - assets/ic_plant_add.svg
    - assets/ic_plant_avatar.png
    - assets/ic_plant_nocircle_more.svg
    - assets/ic_plant_list.svg
    - assets/ic_plant_setting.svg
    - assets/ic_plant_detail.svg
    - assets/ic_plant_gif.png 
    - assets/ic_plant_energy_month.svg
    - assets/ic_plant_energy_day.svg
    - assets/ic_plant_energy_total.svg
    - assets/ic_scan_wifi_tip.png 
    - assets/ic_scan_emu_tip.png 
    - assets/ic_scan_mi_tip.png 
    - assets/ic_scan_gif.gif 
    - assets/ic_scan_blue.gif 
    - assets/ic_signle_mi.png
    - assets/ic_emu.png
    - assets/ic_wifi_mi.png
    - assets/ic_device_delete.png
    - assets/ic_mi_offline_bg.png
    - assets/ic_mi_online_bg.png
    - assets/ic_mi_fault_bg.png
    - assets/ic_mi_fault_gray_bg.png
    - assets/ic_miw_connect.png
    - assets/ic_mi_one.png
    - assets/ic_mi_two.png
    - assets/ic_mi_four.png
    - assets/ic_mi_nine.png
    - assets/ic_connect.png
    - assets/ic_plant_default.png
    - assets/ic_bind_mi.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
